[build]
  functions = "lambda"
  Command = "npm run build"
[build.environment]

  # AWS_S3_ACCESS_KEY = "mega secret"
  # AWS_S3_SECRET_KEY = "super secret"
  # AWS_AZ_REGION = "us-east-1"
  # AWS_S3_BUCKET = "super-bucket"
  NETLIFY_ACCESS_CONTROL_ALLOW_ORIGIN = "*"